version: '3.5'

services:
  ohrbuehl-web-frontend:
    build: ../../frontend
    image: ohrbuehl-frontend
    restart: always
    networks:
      - proxynet
      
  ohrbuehl-web-backend:
    build: ../../backend
    image: ohrbuehl-backend
    restart: always
    environment:
      PORT: 3000
      HOST_URL: https://ohrbuehl.info
      DATABASE_HOST: ohrbuehl-web-mysql-db
      DATABASE_PORT: 3306
      DATABASE_USER: admin
      DATABASE_PASSWORD: 12345
      DATABASE_NAME: ohrbuehl-web
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 465
      MAIL_IGNORE_TLS: "true"
      MAIL_SECURE: "true"
      MAIL_USER: ohrbuehl@gmail.com
      MAIL_PASSWORD: XXX
      APPLICATIONS_PATH: /var/backend/files/applications
    volumes:
      - ../../data/files/applications:/var/backend/files/applications
    links: 
      - ohrbuehl-web-mysql-db
    depends_on:
      - ohrbuehl-web-mysql-db
    networks:
      - proxynet
      
  ohrbuehl-web-mysql-db:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2beer4me@ohrbuehl
      MYSQL_DATABASE: ohrbuehl-web
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    volumes:
      - ../../data/db-data:/var/lib/mysql
    networks:
      - proxynet
      
networks:
  proxynet:
    name: webnet
