version: '3.5'

services:
  ohrbuehl-web-backend:
    build: ../../backend
    image: ohrbuehl-backend
    restart: always
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DATABASE_HOST: ohrbuehl-web-mysql-db
      DATABASE_PORT: 3306
      DATABASE_USER: admin
      DATABASE_PASSWORD: 12345
      DATABASE_NAME: ohrbuehl-web      
    links: 
      - ohrbuehl-web-mysql-db
    depends_on:
      - ohrbuehl-web-mysql-db
    networks:
      - proxynet
      
  ohrbuehl-web-mysql-db:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2beer4me@ohrbuehl
      MYSQL_DATABASE: ohrbuehl-web
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    volumes:
      - .\db-data:/var/lib/mysql
    networks:
      - proxynet

  ohrbuehl-web-phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    links: 
      - ohrbuehl-web-mysql-db
    depends_on:
      - ohrbuehl-web-mysql-db
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: ohrbuehl-web-mysql-db
      PMA_PORT: 3306
    networks:
      - proxynet
      
networks:
  proxynet:
    name: webnet
