version: '3.1'

services:
  backend:
    build: ../../backend
    image: ohrbuehl-backend
    restart: always
    ports:
      - 3000:3000

    environment:
      PORT: 3000
      DATABASE_HOST: mysql-db
      DATABASE_PORT: 3306
      DATABASE_USER: admin
      DATABASE_PASSWORD: 12345
      DATABASE_NAME: ohrbuehl-web      
      
    links: 
      - mysql-db
    depends_on:
      - mysql-db
      
  mysql-db:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2beer4me@ohrbuehl
      MYSQL_DATABASE: ohrbuehl-web
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    volumes:
      - .\db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    links: 
      - mysql-db
    depends_on:
      - mysql-db
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      
