version: '3.5'

services:
  ohrbuehl-web-phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: ohrbuehl-web-mysql-db
      PMA_PORT: 3306
    networks:
      - proxynet
      
networks:
  proxynet:
    name: webnet
