version: '3.1'

services:
  mysql-db:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2beer4me@ohrbuehl
      MYSQL_DATABASE: ohrbuehl-web
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    volumes:
      - .\db-data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    links: 
      - mysql-db
    depends_on:
      - mysql-db
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: mysql-db
      PMA_PORT: 3306

  ohrbuehl-web-frontend:
    build: ../../frontend
    image: ohrbuehl-frontend
    restart: always
    ports:
      - 80:80
      
  ohrbuehl-web-backend:
    build: ../../backend
    image: ohrbuehl-backend
    restart: always
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      HOST_URL: http://localhost
      DATABASE_HOST: mysql-db
      DATABASE_PORT: 3306
      DATABASE_USER: admin
      DATABASE_PASSWORD: 12345
      DATABASE_NAME: ohrbuehl-web
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 465
      MAIL_IGNORE_TLS: "true"
      MAIL_SECURE: "true"
      MAIL_USER: ohrbuehl@gmail.com
      MAIL_PASSWORD: 
      APPLICATIONS_PATH: /var/backend/files/applications
    volumes:
      - ../../data/files/applications:/var/backend/files/applications      
    links: 
      - mysql-db
    depends_on:
      - mysql-db
